[package]
name = "gittles-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true

[build-dependencies]
embed-resource = "3"

[[bin]]
name = "gittles"
path = "src/main.rs"

[dependencies]
gittles-core.workspace = true

anyhow.workspace = true
clap.workspace = true
gpui.workspace = true
gpui-component.workspace = true
jiff.workspace = true
tokio.workspace = true
